"use strict";

const SYMBOLS=["合","乙","老","下老","四","上","中","尺","工","五","六","七","八","○"];
const AUDIO_FILES={"合":"合.wav","乙":"乙.wav","老":"老.wav","下老":"下老.wav","四":"四.wav","上":"上.wav","中":"中.wav","尺":"尺.wav","工":"工.wav","五":"五.wav","六":"六.wav","七":"七.wav","八":"八.wav"};
const TUNING_AUDIO={"本調子":{},"二揚げ":{"四":"二揚四.wav","上":"二揚上.wav","中":"二揚_中.wav"},"三下げ":{"七":"三下七.wav"}};
const KEY_MAP={Digit7:"合",Numpad7:"合",Digit8:"四",Numpad8:"四",Digit9:"工",Numpad9:"工",Digit4:"乙",Numpad4:"乙",Digit5:"上",Numpad5:"上",Digit6:"五",Numpad6:"五",Digit1:"老",Numpad1:"老",Digit2:"中",Numpad2:"中",Digit3:"六",Numpad3:"六",NumpadMultiply:"下老",Digit0:"尺",Numpad0:"尺",Period:"七",NumpadDecimal:"七"};
const $=id=>document.getElementById(id);
const audioBuffers=new Map();
let state,selectedSymbol="合",selectedCol=0,cursorRow=0,selectedSlot="main",selectionActive=true,inputHalfPending=false,history=[],audioCtx=null,activeSources=[],playToken=0,technique="",lyricTool="",markLength=2,chiriMode="",chiriLength=2;

const blankNote=()=>({main:"",half:"",mainSmall:false,halfSmall:false,mainTech:"",halfTech:""});
const blankColumn=()=>({notes:Array.from({length:12},blankNote),lyrics:"",lyricMarks:[],chiriLines:[],visibleRows:12});
const defaultState=()=>safeState(JSON.parse(JSON.stringify(window.KUNKUNSHI_SAMPLE)));

function normalizeNote(value){if(typeof value==="string")return{...blankNote(),main:SYMBOLS.includes(value)?value:""};const note=blankNote();if(value&&typeof value==="object"){note.main=SYMBOLS.includes(value.main)?value.main:"";note.half=SYMBOLS.includes(value.half)?value.half:"";note.mainSmall=Boolean(value.mainSmall);note.halfSmall=Boolean(value.halfSmall);note.mainTech=["uchi","kake"].includes(value.mainTech)?value.mainTech:"";note.halfTech=["uchi","kake"].includes(value.halfTech)?value.halfTech:"";}return note;}
function safeState(raw){if(!raw||!Array.isArray(raw.columns))throw new Error("譜面データの形式が正しくありません。");const markTypes=["start","end","open","filled","hookTopOpen","hookTopFilled","hookBottomOpen","hookBottomFilled"];return{version:6,title:String(raw.title||"無題").slice(0,60),author:String(raw.author||"").slice(0,60),tuning:["本調子","二揚げ","三下げ"].includes(raw.tuning)?raw.tuning:"本調子",tempo:Math.min(180,Math.max(40,Number(raw.tempo)||100)),swingUnit:["none","half","beat"].includes(raw.swingUnit)?raw.swingUnit:"none",swingRatio:Math.min(3,Math.max(1,Number(raw.swingRatio)||2)),columns:raw.columns.slice(0,30).map(column=>{const notes=Array.from({length:12},(_,index)=>normalizeNote(column?.notes?.[index])),lyricMarks=Array.isArray(column?.lyricMarks)?column.lyricMarks.filter(mark=>mark&&markTypes.includes(mark.type)&&Number.isInteger(mark.row)&&mark.row>=0&&mark.row<12).slice(0,24).map(mark=>({...mark,length:Math.min(12-mark.row,Math.max(1,Number(mark.length)||2))})):[],chiriLines=Array.isArray(column?.chiriLines)?column.chiriLines.filter(line=>line&&Number.isInteger(line.row)&&line.row>=0&&line.row<11).slice(0,12).map(line=>({row:line.row,length:Math.min(3,12-line.row,Math.max(2,Number(line.length)||2))})):[],lyrics=String(column?.lyrics||"").slice(0,40);let contentRows=1;notes.forEach((note,index)=>{if(note.main||note.half)contentRows=Math.max(contentRows,index+1);});lyricMarks.forEach(mark=>{contentRows=Math.max(contentRows,mark.row+1);});chiriLines.forEach(line=>{contentRows=Math.max(contentRows,line.row+line.length);});if(lyrics.trim())contentRows=12;const visibleRows=Math.min(12,Math.max(contentRows,Number.isInteger(column?.visibleRows)?column.visibleRows:1));return{notes,lyrics,lyricMarks,chiriLines,visibleRows};})};}
function load(){try{state=safeState(JSON.parse(localStorage.getItem("kunkunshi-score")||"null"));}catch{state=defaultState();}if(!state)state=defaultState();}
function snapshot(){history.push(JSON.stringify(state));if(history.length>30)history.shift();}
function persist(){localStorage.setItem("kunkunshi-score",JSON.stringify(state));$("saveState").textContent="保存済み";setTimeout(()=>$("saveState").textContent="自動保存",1000);}

function scoreLengthBeats(){let last=0;state.columns.forEach((column,ci)=>column.notes.forEach((note,ri)=>{if(note.main||note.half)last=Math.max(last,ci*12+ri+1);}));return last;}
function formatDuration(seconds){if(seconds<=0)return"約0秒";const rounded=Math.round(seconds),minutes=Math.floor(rounded/60),rest=rounded%60;return minutes?`約${minutes}分${rest?`${rest}秒`:""}`:`約${rest}秒`;}
function syncFields(){$("title").value=state.title;$("author").value=state.author;$("tuning").value=state.tuning;$("tempo").value=String(state.tempo);$("tempoOut").value=String(state.tempo);$("paperTitle").textContent=state.title||"無題";$("paperMeta").textContent=[state.author,state.tuning].filter(Boolean).join("・");$("swingRatio").value=String(state.swingRatio);$("swingRatioOut").value=`${state.swingRatio.toFixed(1)}：1`;$("durationOut").textContent=`所要時間：${formatDuration(scoreLengthBeats()*60/state.tempo)}`;document.querySelectorAll("[data-swing]").forEach(button=>button.classList.toggle("active",button.dataset.swing===state.swingUnit));$("swingRatio").disabled=state.swingUnit==="none";}

function makeNoteButton(ci,ri,slot,note){const button=document.createElement("button"),symbol=note[slot];button.className=`${slot==="main"?"noteCell":"halfCell"}${note[`${slot}Small`]?" kubanchi":""}`;if(selectionActive&&ci===selectedCol&&ri===cursorRow&&slot===selectedSlot)button.classList.add("current");button.dataset.col=String(ci);button.dataset.row=String(ri);button.dataset.slot=slot;button.setAttribute("aria-label",`${ci+1}列 ${ri+1}拍 ${slot==="half"?"後半":"頭"} ${symbol||"空欄"}`);if(symbol){const text=document.createElement("span");text.textContent=symbol;if(symbol==="下老")text.className="longSymbol";button.append(text);const tech=note[`${slot}Tech`];if(tech){const mark=document.createElement("i");mark.textContent=tech==="uchi"?"、":"┐";button.append(mark);}}else if(slot==="half")button.textContent="＋";button.onclick=()=>editCell(ci,ri,slot);return button;}
function makeBracketSvg(type,length){const height=Math.max(38,length*40-4),filled=type==="filled"||type.endsWith("Filled"),hookTop=type.startsWith("hookTop"),circleFill=filled?"#222":"#fff";if(hookTop)return`<svg class="bracketSvg" viewBox="0 0 20 ${height}" style="height:${height}px" aria-hidden="true"><line x1="11" y1="${height-10}" x2="11" y2="6" stroke="#222" stroke-width="1.5"/><line x1="11" y1="6" x2="3" y2="6" stroke="#222" stroke-width="1.5"/><circle cx="11" cy="${height-6}" r="4" fill="${circleFill}" stroke="#222"/></svg>`;return`<svg class="bracketSvg" viewBox="0 0 20 ${height}" style="height:${height}px" aria-hidden="true"><circle cx="11" cy="6" r="4" fill="${circleFill}" stroke="#222"/><line x1="11" y1="10" x2="11" y2="${height-6}" stroke="#222" stroke-width="1.5"/><line x1="11" y1="${height-6}" x2="3" y2="${height-6}" stroke="#222" stroke-width="1.5"/></svg>`;}
function visibleBeatCount(column){return Math.min(12,Math.max(1,Number(column.visibleRows)||1));}
function render(){
  syncFields();
  const score=$("score");
  score.replaceChildren();
  state.columns.forEach((column,ci)=>{
    const node=$("columnTemplate").content.firstElementChild.cloneNode(true),visibleRows=visibleBeatCount(column);
    node.style.setProperty("--visibleRows",String(visibleRows));
    node.classList.toggle("selected",selectionActive&&ci===selectedCol);
    node.classList.toggle("screenTrailingHalf",Boolean(column.notes[visibleRows-1]?.half));
    node.classList.toggle("printTrailingHalf",Boolean(column.notes[11]?.half));
    const selector=node.querySelector(".colSelect");
    selector.textContent=String(ci+1);
    selector.onclick=()=>{selectionActive=true;selectedCol=ci;cursorRow=0;selectedSlot="main";render();};
    const cells=node.querySelector(".noteCells");
    column.notes.forEach((note,ri)=>{
      const beat=document.createElement("div");
      beat.className=ri<visibleRows?"beat":"beat trailingEmpty";
      beat.append(makeNoteButton(ci,ri,"main",note),makeNoteButton(ci,ri,"half",note));
      cells.append(beat);
    });
    column.chiriLines.forEach(line=>{
      const marker=document.createElement("span");
      marker.className="chiriLine";
      marker.style.setProperty("--chiri-start",String(line.row));
      marker.style.setProperty("--chiri-length",String(line.length));
      marker.setAttribute("aria-label",`${line.length}音の列音`);
      cells.append(marker);
    });
    const lyrics=node.querySelector(".lyrics"),lyricsPrint=node.querySelector(".lyricsPrint");
    lyrics.value=column.lyrics;
    lyricsPrint.textContent=column.lyrics;
    lyrics.onchange=()=>{snapshot();column.lyrics=lyrics.value;if(column.lyrics.trim())column.visibleRows=12;persist();render();};
    const marks=node.querySelector(".lyricMarks");
    for(let row=0;row<12;row++){
      const button=document.createElement("button"),found=column.lyricMarks.find(mark=>mark.row===row);
      button.className=row<visibleRows?"lyricMark":"lyricMark trailingEmpty";
      if(found){if(found.type==="start")button.textContent="○";else if(found.type==="end")button.textContent="□";else button.innerHTML=makeBracketSvg(found.type,found.length);}
      button.onclick=()=>editLyricMark(ci,row);
      marks.append(button);
    }
    score.append(node);
  });
  updateInputStatus();
}

function editCell(ci,ri,slot){snapshot();selectionActive=true;selectedCol=ci;cursorRow=ri;selectedSlot=slot;const column=state.columns[ci],note=column.notes[ri];if(chiriMode){const index=column.chiriLines.findIndex(line=>line.row===ri);if(chiriMode==="erase"){if(index>=0)column.chiriLines.splice(index,1);}else if(slot==="main"){const length=Math.min(chiriLength,12-ri),value={row:ri,length};if(index>=0)column.chiriLines[index]=value;else if(length>=2)column.chiriLines.push(value);column.visibleRows=Math.max(column.visibleRows||1,ri+length);}persist();render();return;}column.visibleRows=Math.max(column.visibleRows||1,ri+1);if(note[slot]===selectedSymbol){note[slot]="";note[`${slot}Tech`]="";}else{note[slot]=selectedSymbol;note[`${slot}Small`]=false;note[`${slot}Tech`]=technique;}persist();render();}
function previousBeat(){if(cursorRow>0)return{col:selectedCol,row:cursorRow-1};if(selectedCol>0)return{col:selectedCol-1,row:11};return null;}
function setHalfPending(value){inputHalfPending=value;$("beatInputBtn").classList.toggle("active",!value);$("halfInputBtn").classList.toggle("active",value);updateInputStatus();}
function updateInputStatus(){const status=$("inputStatus");if(status)status.textContent=inputHalfPending?`${selectedCol+1}列・${cursorRow+1}拍目の直前へ半拍入力`:`${selectedCol+1}列・${cursorRow+1}拍目へ1拍入力`;}
function advanceCursor(){cursorRow++;if(cursorRow>=12){cursorRow=0;if(selectedCol<state.columns.length-1)selectedCol++;}}
function insertFromKeypad(symbol,half=inputHalfPending){if(!SYMBOLS.includes(symbol))return;let target={col:selectedCol,row:cursorRow},slot="main";if(half){const previous=previousBeat();if(!previous){setHalfPending(false);alert("最初の1拍より前には半拍を入力できません。");return;}target=previous;slot="half";}snapshot();selectedSymbol=symbol;updateKandoSelection();const column=state.columns[target.col],note=column.notes[target.row];column.visibleRows=Math.max(column.visibleRows||1,target.row+1);note[slot]=symbol;note[`${slot}Small`]=false;note[`${slot}Tech`]=technique;if(!half)advanceCursor();selectedSlot="main";setHalfPending(false);persist();render();}
function handleKeyboard(event){const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement)return;if(event.code==="ShiftLeft"||event.code==="ShiftRight"){event.preventDefault();if(!event.repeat)setHalfPending(true);return;}const half=event.shiftKey||inputHalfPending;if(event.ctrlKey&&(event.code==="Slash"||event.code==="NumpadDivide")){event.preventDefault();insertFromKeypad("八",half);return;}const symbol=KEY_MAP[event.code];if(!symbol)return;event.preventDefault();insertFromKeypad(symbol,half);}

function editLyricMark(ci,row){if(!lyricTool){alert("先に歌の記号を選んでください。");return;}snapshot();const column=state.columns[ci],marks=column.lyricMarks,index=marks.findIndex(mark=>mark.row===row);column.visibleRows=Math.max(column.visibleRows||1,row+1);if(lyricTool==="erase"){if(index>=0)marks.splice(index,1);}else{const value={row,type:lyricTool,length:Math.min(12-row,markLength)};if(index>=0)marks[index]=value;else marks.push(value);}selectedCol=ci;persist();render();}
function updateKandoSelection(){const doc=$("kandoObject")?.contentDocument;if(!doc)return;doc.querySelectorAll("[data-note]").forEach(item=>item.classList.toggle("active",item.dataset.note===selectedSymbol));}
function bindKando(){const object=$("kandoObject");if(!object)return;const attach=()=>{const doc=object.contentDocument;if(!doc)return;doc.querySelectorAll("[data-note]").forEach(item=>{item.onclick=()=>{insertFromKeypad(item.dataset.note||"");clearScoreSelection();};item.onkeydown=event=>{if(event.key!=="Enter"&&event.key!==" ")return;event.preventDefault();insertFromKeypad(item.dataset.note||"");clearScoreSelection();};});updateKandoSelection();};object.addEventListener("load",attach);attach();}
function bindHelpDialog(dialogId,openId,closeId){const dialog=$(dialogId),open=$(openId),close=$(closeId);if(!dialog||!open||!close)return;const closeDialog=()=>{if(typeof dialog.close==="function")dialog.close();else dialog.removeAttribute("open");};open.onclick=()=>{if(typeof dialog.showModal==="function")dialog.showModal();else dialog.setAttribute("open","");};close.onclick=closeDialog;dialog.addEventListener("click",event=>{if(event.target===dialog)closeDialog();});}
function bindHelpDialogs(){bindHelpDialog("swingHelpDialog","swingHelpBtn","swingHelpClose");bindHelpDialog("tempoHelpDialog","tempoHelpBtn","tempoHelpClose");}
function eraseSelectedNote(){const note=state.columns[selectedCol]?.notes[cursorRow];if(!note)return;snapshot();note[selectedSlot]="";note[`${selectedSlot}Small`]=false;note[`${selectedSlot}Tech`]="";persist();render();}
function setChoice(ids,callback){ids.forEach(id=>{const control=$(id);if(!control)return;control.onclick=()=>{ids.forEach(item=>$(item)?.classList.toggle("active",item===id));callback(id);};});}
function updateMeta(){snapshot();state.title=$("title").value;state.author=$("author").value;state.tuning=$("tuning").value;state.tempo=Number($("tempo").value);persist();syncFields();}
function clearScoreSelection(){selectionActive=false;document.querySelectorAll(".noteCell.current,.halfCell.current,.scoreCol.selected").forEach(item=>item.classList.remove("current","selected"));}
function chiriAnchor(column,row){const line=column.chiriLines.find(item=>row>=item.row&&row<item.row+item.length);return line?line.row:row;}
function buildPrintPages(){const container=$("printPages"),sourceCols=[...$("score").children],title=$("paper").querySelector(".paperTitle"),legend=document.querySelector(".notationLegend");container.replaceChildren();for(let start=0;start<sourceCols.length;start+=10){const sheet=document.createElement("section"),paper=document.createElement("div"),body=document.createElement("div"),score=document.createElement("div"),chunk=sourceCols.slice(start,start+10);sheet.className=chunk.length<10?"printSheet partial":"printSheet";paper.className="paper printPaper";body.className="paperBody";score.className="score";chunk.forEach(column=>score.append(column.cloneNode(true)));if(start===0){const titleClone=title.cloneNode(true);titleClone.querySelectorAll("[id]").forEach(item=>item.removeAttribute("id"));body.append(titleClone);}body.append(score);paper.append(body,legend.cloneNode(true));sheet.append(paper);container.append(sheet);}container.setAttribute("aria-hidden","false");}
function bindExtended(){const setChiriMode=mode=>{chiriMode=mode;$("chiriBtn").classList.toggle("active",mode==="add");$("chiriEraseBtn").classList.toggle("active",mode==="erase");};$("chiriBtn").onclick=()=>setChiriMode(chiriMode==="add"?"":"add");$("chiriEraseBtn").onclick=()=>setChiriMode(chiriMode==="erase"?"":"erase");$("chiriLength").oninput=()=>{chiriLength=Number($("chiriLength").value);$("chiriLengthOut").value=`${chiriLength}音`;};["techNoneBtn","uchiBtn","kakeBtn"].forEach(id=>$(id).addEventListener("click",()=>setChiriMode("")));$("addColBtn").onclick=()=>{snapshot();const added=blankColumn();added.visibleRows=12;state.columns.splice(selectedCol+1,0,added);selectedCol++;cursorRow=0;selectedSlot="main";selectionActive=true;persist();render();};$("printBtn").onclick=()=>{buildPrintPages();window.print();};window.addEventListener("beforeprint",buildPrintPages);document.addEventListener("click",event=>{if(event.target instanceof Element&&!event.target.closest(".scoreCol"))clearScoreSelection();});}

function audioFile(symbol){return TUNING_AUDIO[state.tuning]?.[symbol]||AUDIO_FILES[symbol]||"";}
async function getBuffer(file){if(audioBuffers.has(file))return audioBuffers.get(file);const response=await fetch(`audio/${encodeURIComponent(file)}`);if(!response.ok)throw new Error(`音源 ${file} を読み込めません。`);const buffer=await audioCtx.decodeAudioData(await response.arrayBuffer());audioBuffers.set(file,buffer);return buffer;}
function stop(){playToken++;activeSources.forEach(source=>{try{source.stop();}catch{}});activeSources=[];document.querySelectorAll(".playing").forEach(node=>node.classList.remove("playing"));$("playStatus").textContent="停止中";}
function showPlayingNote(ci,ri,slot){document.querySelectorAll(".playing").forEach(node=>node.classList.remove("playing"));const note=document.querySelector(`[data-col="${ci}"][data-row="${ri}"][data-slot="${slot}"]`),wrap=document.querySelector(".paperWrap");if(!note||!wrap)return;note.classList.add("playing");const noteRect=note.getBoundingClientRect(),wrapRect=wrap.getBoundingClientRect(),distance=noteRect.left+noteRect.width/2-(wrapRect.left+wrapRect.width/2);if(Math.abs(distance)>Math.max(24,wrapRect.width*.18))wrap.scrollBy({left:distance,behavior:"smooth"});}
function playBuffer(buffer,when,small){const source=audioCtx.createBufferSource(),gain=audioCtx.createGain();source.buffer=buffer;gain.gain.value=small?.4:1;source.connect(gain).connect(audioCtx.destination);source.start(when);activeSources.push(source);}
function swungBeatTime(time){const ratio=state.swingRatio;if(state.swingUnit==="half"){const whole=Math.floor(time),fraction=time-whole;if(Math.abs(fraction-.5)<.01)return whole+ratio/(ratio+1);return time;}if(state.swingUnit==="beat"){const pair=Math.floor(time/2),inside=time-pair*2,long=2*ratio/(ratio+1),short=2/(ratio+1);return pair*2+(inside<=1?inside*long:long+(inside-1)*short);}return time;}
async function play(){stop();try{audioCtx=audioCtx||new AudioContext();await audioCtx.resume();const token=++playToken,beat=60/state.tempo,events=[];state.columns.forEach((column,ci)=>column.notes.forEach((note,ri)=>{const base=ci*12+ri;if(note.main&&note.main!=="○")events.push({symbol:note.main,ci,ri,slot:"main",small:note.mainSmall,time:ci*12+chiriAnchor(column,ri)});if(note.half&&note.half!=="○")events.push({symbol:note.half,ci,ri,slot:"half",small:note.halfSmall,time:base+.5});}));if(!events.length){$("playStatus").textContent="音が入力されていません";return;}$("playStatus").textContent="三線音源を準備中";const unique=[...new Set(events.map(event=>audioFile(event.symbol)))];await Promise.all(unique.map(getBuffer));if(token!==playToken)return;$("playStatus").textContent="演奏中";const start=audioCtx.currentTime+.12;events.forEach((event,index)=>{const when=start+swungBeatTime(event.time)*beat;playBuffer(audioBuffers.get(audioFile(event.symbol)),when,event.small);setTimeout(()=>{if(token!==playToken)return;showPlayingNote(event.ci,event.ri,event.slot);if(index===events.length-1)setTimeout(stop,900);},Math.max(0,(when-audioCtx.currentTime)*1000));});}catch(error){stop();$("playStatus").textContent=error instanceof Error?error.message:"音源の再生に失敗しました";}}
function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=`${(state.title||"工工四").replace(/[\\/:*?\"<>|]/g,"_")}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),1000);}

function bind(){["title","author","tuning"].forEach(id=>$(id).addEventListener("change",updateMeta));$("tempo").oninput=()=>{$("tempoOut").value=$("tempo").value;};$("tempo").onchange=updateMeta;document.querySelectorAll("[data-swing]").forEach(button=>button.onclick=()=>{snapshot();state.swingUnit=button.dataset.swing||"none";persist();syncFields();});$("swingRatio").oninput=()=>{$("swingRatioOut").value=`${Number($("swingRatio").value).toFixed(1)}：1`;};$("swingRatio").onchange=()=>{snapshot();state.swingRatio=Number($("swingRatio").value);persist();syncFields();};setChoice(["techNoneBtn","uchiBtn","kakeBtn"],id=>technique=id==="uchiBtn"?"uchi":id==="kakeBtn"?"kake":"");document.querySelectorAll("[data-lyric-symbol]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-lyric-symbol]").forEach(item=>item.classList.remove("active"));button.classList.add("active");lyricTool=button.dataset.lyricSymbol||"";});$("markLength").oninput=()=>{markLength=Number($("markLength").value);$("markLengthOut").value=`${markLength}拍`;};$("beatInputBtn").onclick=()=>setHalfPending(false);$("halfInputBtn").onclick=()=>setHalfPending(!inputHalfPending);document.querySelectorAll("[data-note]").forEach(button=>button.addEventListener("click",()=>insertFromKeypad(button.dataset.note||"")));document.addEventListener("keydown",handleKeyboard);$("sampleBtn").onclick=()=>{if(confirm("現在の譜面を童神の見本に置き換えますか？")){snapshot();state=defaultState();selectedCol=0;cursorRow=0;persist();render();}};$("newBtn").onclick=()=>{if(confirm("12マス×10列の新しい空の譜面を作りますか？")){snapshot();state={...defaultState(),title:"無題",author:"",columns:Array.from({length:10},blankColumn)};selectedCol=0;cursorRow=0;selectedSlot="main";selectionActive=true;persist();render();}};$("addColBtn").onclick=()=>{snapshot();state.columns.splice(selectedCol+1,0,blankColumn());selectedCol++;cursorRow=0;persist();render();};$("removeColBtn").onclick=()=>{if(state.columns.length<=1)return;snapshot();state.columns.splice(selectedCol,1);selectedCol=Math.max(0,selectedCol-1);cursorRow=0;persist();render();};$("eraseBtn").onclick=()=>{snapshot();state.columns[selectedCol].notes=Array.from({length:12},blankNote);persist();render();};$("undoBtn").onclick=()=>{const previous=history.pop();if(previous){state=safeState(JSON.parse(previous));persist();render();}};$("exportBtn").onclick=download;$("printBtn").onclick=()=>window.print();$("playBtn").onclick=play;$("stopBtn").onclick=stop;$("importFile").onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{snapshot();state=safeState(JSON.parse(await file.text()));selectedCol=0;cursorRow=0;persist();render();}catch(error){alert(error instanceof Error?error.message:"読み込みに失敗しました。");}finally{event.target.value="";}};document.addEventListener("visibilitychange",()=>{if(document.hidden)stop();});window.addEventListener("beforeunload",stop);}

load();bind();bindExtended();bindKando();bindHelpDialogs();$("eraseNoteBtn").onclick=eraseSelectedNote;render();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
