"use strict";
const SYMBOLS=["合","乙","老","下老","四","上","中","尺","工","五","六","七","八","○"],FILES={合:"合.wav",乙:"乙.wav",老:"老.wav",下老:"下老.wav",四:"四.wav",上:"上.wav",中:"中.wav",尺:"尺.wav",工:"工.wav",五:"五.wav",六:"六.wav",七:"七.wav",八:"八.wav"},TUNING={"本調子":{},"二揚げ":{四:"二揚四.wav",上:"二揚上.wav",中:"二揚_中.wav"},"三下げ":{七:"三下七.wav"}},KANDO={合:"合.png",乙:"乙.png",老:"老.png",下老:"下老.png",四:"四.png",上:"上.png",中:"中.png",尺:"尺.png",工:"工.png",五:"五.png",六:"六.png",七:"七.png",八:"八.png","○":"○.png"},PRACTICE_NOTE_POSITION={工:[0,0],五:[0,1],六:[0,2],七:[0,3],八:[0,4],四:[1,0],上:[1,1],中:[1,2],尺:[1,3],合:[2,0],乙:[2,1],老:[2,2],下老:[2,3]},$=id=>document.getElementById(id);
let state,ctx,gain,sources=[],timers=[],token=0,paused=0,started=0,originBeat=0,playing=false;const buffers=new Map();
function note(v){const b={main:"",half:"",mainSmall:false,halfSmall:false,mainTech:"",halfTech:""};if(typeof v==="string")return{...b,main:SYMBOLS.includes(v)?v:""};if(!v||typeof v!=="object")return b;return{main:SYMBOLS.includes(v.main)?v.main:"",half:SYMBOLS.includes(v.half)?v.half:"",mainSmall:!!v.mainSmall,halfSmall:!!v.halfSmall,mainTech:["uchi","kake"].includes(v.mainTech)?v.mainTech:"",halfTech:["uchi","kake"].includes(v.halfTech)?v.halfTech:""};}
function safe(raw){if(!raw||!Array.isArray(raw.columns)||!raw.columns.length)throw new Error("工工四エディターのJSON形式ではありません。");if(raw.columns.length>100)throw new Error("列数が多すぎるため読み込めません。");return{title:String(raw.title||"無題").slice(0,60),author:String(raw.author||"").slice(0,60),tuning:["本調子","二揚げ","三下げ"].includes(raw.tuning)?raw.tuning:"本調子",tempo:Math.min(180,Math.max(40,Number(raw.tempo)||100)),swingUnit:["none","half","beat"].includes(raw.swingUnit)?raw.swingUnit:"none",swingRatio:Math.min(3,Math.max(1,Number(raw.swingRatio)||2)),columns:raw.columns.map(c=>({notes:Array.from({length:12},(_,i)=>note(c?.notes?.[i])),lyrics:String(c?.lyrics||"").slice(0,80)}))};}
function glyph(el,symbol,small,tech){if(!symbol)return;const g=document.createElement("span");g.className=`noteGlyph${small?" small":""}`;g.textContent=symbol;el.append(g);if(tech){const m=document.createElement("i");m.className="techMark";m.textContent=tech==="uchi"?"、":"┐";el.append(m);}}
function renderScore(score){score.replaceChildren();[...state.columns].map((column,ci)=>({column,ci})).reverse().forEach(({column:c,ci})=>{const col=document.createElement("div"),number=document.createElement("span"),cells=document.createElement("div"),lyrics=document.createElement("div");col.className="scoreCol";col.dataset.scoreCol=String(ci);number.className="columnNumber";number.textContent=String(ci+1);cells.className="noteCells";c.notes.forEach((n,ri)=>{const row=document.createElement("div");row.className="noteRow";Object.assign(row.dataset,{col:ci,row:ri,slot:"main"});glyph(row,n.main,n.mainSmall,n.mainTech);if(n.half){const half=document.createElement("div");half.className="halfCell";Object.assign(half.dataset,{col:ci,row:ri,slot:"half"});glyph(half,n.half,n.halfSmall,n.halfTech);row.append(half);}cells.append(row);});lyrics.className="lyricLane";lyrics.textContent=c.lyrics;col.append(number,cells,lyrics);score.append(col);});}
function practiceNotesForColumn(column){const notes=[];column?.notes?.forEach((item,row)=>{if(item.main)notes.push({symbol:item.main,row,slot:"main",beat:row});if(item.half)notes.push({symbol:item.half,row,slot:"half",beat:row+.5});});return notes;}
function makePracticeColumn(column,index){const section=document.createElement("section"),heading=document.createElement("h3"),lane=document.createElement("div");section.className="laneColumn";section.dataset.laneCol=String(index);heading.textContent=`${index+1}列目`;lane.className="laneNoteTrack";section.append(heading);const notes=practiceNotesForColumn(column);if(!notes.length){const empty=document.createElement("span");empty.className="laneEmpty";empty.textContent="休み";lane.append(empty);}notes.forEach(item=>{const position=PRACTICE_NOTE_POSITION[item.symbol],marker=document.createElement("span");marker.className=`laneNote ${item.slot}`;marker.dataset.laneRow=String(item.row);marker.dataset.laneSlot=item.slot;marker.textContent=item.symbol;marker.title=position?`${["三弦","二弦","一弦"][position[0]]}・${position[1]===0?"開放弦":`${position[1]}番目の勘所`}`:item.symbol;marker.style.setProperty("--left",`${8+item.beat/12*88}%`);marker.style.setProperty("--top",`${((position?.[0]??1)*2+1)/6*100}%`);lane.append(marker);});section.append(lane);return section;}
function renderPracticeColumns(activeEvent=null){const host=$("laneColumns"),viewport=host?.closest(".laneViewport");if(!host||!viewport||!state)return;if(host.children.length!==state.columns.length){host.replaceChildren(...state.columns.map(makePracticeColumn));viewport.scrollLeft=0;}const current=Math.max(0,Math.min(state.columns.length-1,activeEvent?.ci??0));host.querySelectorAll(".laneColumn").forEach((column,index)=>column.classList.toggle("current",index===current));host.querySelectorAll(".laneNote.playing").forEach(marker=>marker.classList.remove("playing"));if(activeEvent){const marker=host.querySelector(`[data-lane-col="${current}"] [data-lane-row="${activeEvent.ri}"][data-lane-slot="${activeEvent.slot}"]`);marker?.classList.add("playing");}const columnWidth=host.firstElementChild?.getBoundingClientRect().width||viewport.clientWidth;viewport.scrollTo({left:current*columnWidth,behavior:activeEvent?"smooth":"auto"});}
function render(){$("songTitle").textContent=state.title;$("songAuthor").textContent=state.author||"―";$("songTuning").textContent=state.tuning;$("paperTitle").textContent=state.title;$("paperMeta").textContent=[state.author,state.tuning].filter(Boolean).join("・");$("tempo").value=state.tempo;$("tempoOut").textContent=`${state.tempo} BPM`;renderScore($("score"));$("laneColumns").replaceChildren();renderPracticeColumns();renderNoteWindow();requestAnimationFrame(()=>{const viewport=$("fullScoreViewport");viewport.scrollLeft=viewport.scrollWidth-viewport.clientWidth;});}
const file=s=>TUNING[state.tuning]?.[s]||FILES[s]||"";
async function buffer(f){if(buffers.has(f))return buffers.get(f);const r=await fetch(`audio/${encodeURIComponent(f)}`);if(!r.ok)throw new Error(`音源「${f}」を読み込めません。`);const b=await ctx.decodeAudioData(await r.arrayBuffer());buffers.set(f,b);return b;}
function list(){const a=[];state.columns.forEach((c,ci)=>c.notes.forEach((n,ri)=>{const beat=ci*12+ri;if(n.main)a.push({symbol:n.main,ci,ri,slot:"main",small:n.mainSmall,beat,sound:n.main!=="○"});if(n.half)a.push({symbol:n.half,ci,ri,slot:"half",small:n.halfSmall,beat:beat+.5,sound:n.half!=="○"});}));return a;}
function renderNoteWindow(activeEvent=null){const host=$("noteWindow");if(!host)return;const events=state?.columns?list():[],labels=["前の音","現在の音","次の音","2つ先","3つ先"],offsets=[-1,0,1,2,3];let current=-1;if(activeEvent)current=events.findIndex(e=>e.ci===activeEvent.ci&&e.ri===activeEvent.ri&&e.slot===activeEvent.slot);host.replaceChildren(...offsets.map((offset,index)=>{const card=document.createElement("div"),label=document.createElement("span"),value=document.createElement("strong"),event=current>=0?events[current+offset]:null;card.className=`flowNoteCard ${offset<0?"past":offset===0?"current":"next"}${event?.slot==="half"?" halfBeat":""}`;label.textContent=labels[index];value.textContent=event?.symbol||"―";if(offset===0)value.id="currentNote";card.append(label,value);if(event?.slot==="half"){const half=document.createElement("small");half.textContent="半拍";card.append(half);}return card;}));if(activeEvent)host.querySelectorAll(".flowNoteCard strong").forEach(value=>value.animate?.([{opacity:.28},{opacity:1}],{duration:280,easing:"ease-out"}));}
function swing(x){const r=state.swingRatio;if(state.swingUnit==="half"){const w=Math.floor(x);return Math.abs(x-w-.5)<.01?w+r/(r+1):x;}if(state.swingUnit==="beat"){const p=Math.floor(x/2),i=x-p*2,l=2*r/(r+1),s=2/(r+1);return p*2+(i<=1?i*l:l+(i-1)*s);}return x;}
function clear(){token++;sources.forEach(s=>{try{s.stop();}catch{}});sources=[];timers.forEach(clearTimeout);timers=[];document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));playing=false;}
function status(s){$("playStatus").textContent=s;}function error(e){$("errorMessage").hidden=false;$("errorMessage").textContent=e instanceof Error?e.message:"処理に失敗しました。";}function hideError(){$("errorMessage").hidden=true;}
function setKando(symbol){const current=$("currentNote"),svg=$("kandoSvg"),isRest=symbol==="○",active=symbol&&!isRest?symbol:"";if(current)current.textContent=symbol||"―";if(!svg)return;svg.classList.toggle("isRest",isRest);svg.classList.toggle("hasActive",Boolean(active));svg.querySelectorAll(".kandoMarker").forEach(marker=>marker.classList.toggle("active",marker.dataset.symbol===active));const title=$("kandoSvgTitle");if(title)title.textContent=isRest?"休符":active?`工工四「${active}」の三線の勘所`:"三線の勘所";}
function followScore(node){const viewport=node?.closest(".scoreViewport"),column=node?.closest(".scoreCol");if(!viewport||!column)return;const frame=viewport.getBoundingClientRect(),box=column.getBoundingClientRect();const target=viewport.scrollLeft+box.left+box.width/2-frame.left-frame.width/2;viewport.scrollTo({left:Math.max(0,Math.min(viewport.scrollWidth-viewport.clientWidth,target)),behavior:"smooth"});}
function highlight(e){document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));setKando(e.symbol);renderNoteWindow(e);renderPracticeColumns(e);document.querySelectorAll(`[data-col="${e.ci}"][data-row="${e.ri}"][data-slot="${e.slot}"]`).forEach(n=>{n.classList.add("playing");followScore(n);});}
async function play(from=0){clear();hideError();try{const all=list().filter(e=>e.beat>=from);if(!all.length){status("演奏する音がありません");return;}ctx||=new AudioContext();await ctx.resume();if(!gain){gain=ctx.createGain();gain.connect(ctx.destination);}gain.gain.value=Number($("volume").value)/100;status("三線音源を準備中");await Promise.all([...new Set(all.filter(e=>e.sound).map(e=>file(e.symbol)))].map(buffer));const t=++token,spb=60/state.tempo,start=ctx.currentTime+.12;started=ctx.currentTime;originBeat=from;playing=true;$("pauseBtn").disabled=false;$("pauseBtn").textContent="Ⅱ 一時停止";status("演奏中");all.forEach((e,i)=>{const when=start+Math.max(0,swing(e.beat)-swing(from))*spb;if(e.sound){const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=buffers.get(file(e.symbol));g.gain.value=e.small?.4:1;s.connect(g).connect(gain);s.start(when);sources.push(s);}timers.push(setTimeout(()=>{if(t!==token)return;highlight(e);if(i===all.length-1)timers.push(setTimeout(stop,900));},Math.max(0,(when-ctx.currentTime)*1000)));});}catch(e){clear();status("再生できませんでした");error(e);}}
function pause(){if(playing){paused=originBeat+Math.max(0,(ctx.currentTime-started)*state.tempo/60);clear();$("pauseBtn").disabled=false;$("pauseBtn").textContent="▶ 続きから再開";status("一時停止中");}else if(paused>0)play(paused);}
function stop(){clear();paused=0;$("pauseBtn").disabled=true;$("pauseBtn").textContent="Ⅱ 一時停止";status("停止中");setKando("");renderNoteWindow();renderPracticeColumns();}
function load(raw){stop();state=safe(raw);render();hideError();setKando("");}
const BUILTINS={warabigami:window.KUNKUNSHI_SAMPLE,...(window.KUNKUNSHI_LEGACY_SONGS||{})};
const builtinEntries=Object.entries(BUILTINS).filter(([,song])=>song&&Array.isArray(song.columns));
function chooseBuiltin(key){const song=BUILTINS[key];if(!song){error(new Error("内蔵曲を読み込めませんでした。"));return;}$("builtinSelect").value=key;load(song);document.querySelectorAll(".builtinSongBtn").forEach(button=>button.classList.toggle("active",button.dataset.songKey===key));}
builtinEntries.forEach(([key,song])=>{const option=document.createElement("option");option.value=key;option.textContent=song.title;$("builtinSelect").append(option);const button=document.createElement("button");button.type="button";button.className="builtinSongBtn";button.dataset.songKey=key;button.textContent=song.title;button.onclick=()=>chooseBuiltin(key);$("builtinSongs").append(button);});
if(!builtinEntries.length)error(new Error("内蔵曲データがありません。"));
$("builtinBtn").onclick=()=>chooseBuiltin($("builtinSelect").value);$("builtinSelect").onchange=()=>chooseBuiltin($("builtinSelect").value);$("importFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{load(JSON.parse(await f.text()));document.querySelectorAll(".builtinSongBtn").forEach(button=>button.classList.remove("active"));}catch(x){error(x);}finally{e.target.value="";}};$("tempo").oninput=()=>{state.tempo=Number($("tempo").value);$("tempoOut").textContent=`${state.tempo} BPM`;};$("volume").oninput=()=>{const v=Number($("volume").value);$("volumeOut").textContent=`${v}%`;if(gain)gain.gain.value=v/100;};$("playBtn").onclick=()=>{paused=0;play(0);};$("pauseBtn").onclick=pause;$("stopBtn").onclick=stop;document.addEventListener("visibilitychange",()=>{if(document.hidden&&playing)pause();});window.addEventListener("beforeunload",stop);try{chooseBuiltin("warabigami");}catch(e){error(e);}
$("paletteToggle").onchange=()=>{$("practiceStage").hidden=!$("paletteToggle").checked;};
$("laneToggle").onchange=()=>{$("laneBody").hidden=!$("laneToggle").checked;};
