"use strict";
const SYMBOLS=["合","乙","老","下老","四","上","中","尺","工","五","六","七","八","○"],FILES={合:"合.wav",乙:"乙.wav",老:"老.wav",下老:"下老.wav",四:"四.wav",上:"上.wav",中:"中.wav",尺:"尺.wav",工:"工.wav",五:"五.wav",六:"六.wav",七:"七.wav",八:"八.wav"},TUNING={"本調子":{},"二揚げ":{四:"二揚四.wav",上:"二揚上.wav",中:"二揚_中.wav"},"三下げ":{七:"三下七.wav"}},KANDO={合:"合.gif",乙:"乙.gif",老:"老.gif",下老:"下老.gif",四:"四.gif",上:"上.gif",中:"中.gif",尺:"尺.gif",工:"工.gif",五:"五.gif",六:"六.gif",七:"七.gif",八:"八.gif","○":"○.gif"},$=id=>document.getElementById(id);
let state,ctx,gain,sources=[],timers=[],token=0,paused=0,started=0,originBeat=0,playing=false;const buffers=new Map();
function note(v){const b={main:"",half:"",mainSmall:false,halfSmall:false,mainTech:"",halfTech:""};if(typeof v==="string")return{...b,main:SYMBOLS.includes(v)?v:""};if(!v||typeof v!=="object")return b;return{main:SYMBOLS.includes(v.main)?v.main:"",half:SYMBOLS.includes(v.half)?v.half:"",mainSmall:!!v.mainSmall,halfSmall:!!v.halfSmall,mainTech:["uchi","kake"].includes(v.mainTech)?v.mainTech:"",halfTech:["uchi","kake"].includes(v.halfTech)?v.halfTech:""};}
function safe(raw){if(!raw||!Array.isArray(raw.columns)||!raw.columns.length)throw new Error("工工四エディターのJSON形式ではありません。");if(raw.columns.length>100)throw new Error("列数が多すぎるため読み込めません。");return{title:String(raw.title||"無題").slice(0,60),author:String(raw.author||"").slice(0,60),tuning:["本調子","二揚げ","三下げ"].includes(raw.tuning)?raw.tuning:"本調子",tempo:Math.min(180,Math.max(40,Number(raw.tempo)||100)),swingUnit:["none","half","beat"].includes(raw.swingUnit)?raw.swingUnit:"none",swingRatio:Math.min(3,Math.max(1,Number(raw.swingRatio)||2)),columns:raw.columns.map(c=>({notes:Array.from({length:12},(_,i)=>note(c?.notes?.[i])),lyrics:String(c?.lyrics||"").slice(0,80)}))};}
function glyph(el,symbol,small,tech){if(!symbol)return;const g=document.createElement("span");g.className=`noteGlyph${small?" small":""}`;g.textContent=symbol;el.append(g);if(tech){const m=document.createElement("i");m.className="techMark";m.textContent=tech==="uchi"?"、":"┐";el.append(m);}}
function render(){$("songTitle").textContent=state.title;$("songAuthor").textContent=state.author||"―";$("songTuning").textContent=state.tuning;$("paperTitle").textContent=state.title;$("paperMeta").textContent=[state.author,state.tuning].filter(Boolean).join("・");$("tempo").value=state.tempo;$("tempoOut").textContent=`${state.tempo} BPM`;const score=$("score");score.replaceChildren();state.columns.forEach((c,ci)=>{const col=document.createElement("div"),cells=document.createElement("div"),lyrics=document.createElement("div");col.className="scoreCol";cells.className="noteCells";c.notes.forEach((n,ri)=>{const row=document.createElement("div");row.className="noteRow";Object.assign(row.dataset,{col:ci,row:ri,slot:"main"});glyph(row,n.main,n.mainSmall,n.mainTech);if(n.half){const half=document.createElement("div");half.className="halfCell";Object.assign(half.dataset,{col:ci,row:ri,slot:"half"});glyph(half,n.half,n.halfSmall,n.halfTech);row.append(half);}cells.append(row);});lyrics.className="lyricLane";lyrics.textContent=c.lyrics;col.append(cells,lyrics);score.append(col);});}
const file=s=>TUNING[state.tuning]?.[s]||FILES[s]||"";
async function buffer(f){if(buffers.has(f))return buffers.get(f);const r=await fetch(`audio/${encodeURIComponent(f)}`);if(!r.ok)throw new Error(`音源「${f}」を読み込めません。`);const b=await ctx.decodeAudioData(await r.arrayBuffer());buffers.set(f,b);return b;}
function list(){const a=[];state.columns.forEach((c,ci)=>c.notes.forEach((n,ri)=>{const beat=ci*12+ri;if(n.main)a.push({symbol:n.main,ci,ri,slot:"main",small:n.mainSmall,beat,sound:n.main!=="○"});if(n.half)a.push({symbol:n.half,ci,ri,slot:"half",small:n.halfSmall,beat:beat+.5,sound:n.half!=="○"});}));return a;}
function swing(x){const r=state.swingRatio;if(state.swingUnit==="half"){const w=Math.floor(x);return Math.abs(x-w-.5)<.01?w+r/(r+1):x;}if(state.swingUnit==="beat"){const p=Math.floor(x/2),i=x-p*2,l=2*r/(r+1),s=2/(r+1);return p*2+(i<=1?i*l:l+(i-1)*s);}return x;}
function clear(){token++;sources.forEach(s=>{try{s.stop();}catch{}});sources=[];timers.forEach(clearTimeout);timers=[];document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));playing=false;}
function status(s){$("playStatus").textContent=s;}function error(e){$("errorMessage").hidden=false;$("errorMessage").textContent=e instanceof Error?e.message:"処理に失敗しました。";}function hideError(){$("errorMessage").hidden=true;}
function setKando(symbol){$("currentNote").textContent=symbol||"―";$("kandoImage").src=symbol&&KANDO[symbol]?`legacy-img/${KANDO[symbol]}`:"legacy-img/tindami2.gif";$("kandoImage").alt=symbol?`工工四「${symbol}」の三線の勘所`:"三線の勘所";}
function highlight(e){document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));const n=document.querySelector(`[data-col="${e.ci}"][data-row="${e.ri}"][data-slot="${e.slot}"]`),w=document.querySelector(".paperWrap");setKando(e.symbol);if(!n)return;n.classList.add("playing");const a=n.getBoundingClientRect(),b=w.getBoundingClientRect();w.scrollBy({left:a.left+a.width/2-b.left-b.width/2,behavior:"smooth"});}
async function play(from=0){clear();hideError();try{const all=list().filter(e=>e.beat>=from);if(!all.length){status("演奏する音がありません");return;}ctx||=new AudioContext();await ctx.resume();if(!gain){gain=ctx.createGain();gain.connect(ctx.destination);}gain.gain.value=Number($("volume").value)/100;status("三線音源を準備中");await Promise.all([...new Set(all.filter(e=>e.sound).map(e=>file(e.symbol)))].map(buffer));const t=++token,spb=60/state.tempo,start=ctx.currentTime+.12;started=ctx.currentTime;originBeat=from;playing=true;$("pauseBtn").disabled=false;$("pauseBtn").textContent="Ⅱ 一時停止";status("演奏中");all.forEach((e,i)=>{const when=start+Math.max(0,swing(e.beat)-swing(from))*spb;if(e.sound){const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=buffers.get(file(e.symbol));g.gain.value=e.small?.4:1;s.connect(g).connect(gain);s.start(when);sources.push(s);}timers.push(setTimeout(()=>{if(t!==token)return;highlight(e);if(i===all.length-1)timers.push(setTimeout(stop,900));},Math.max(0,(when-ctx.currentTime)*1000)));});}catch(e){clear();status("再生できませんでした");error(e);}}
function pause(){if(playing){paused=originBeat+Math.max(0,(ctx.currentTime-started)*state.tempo/60);clear();$("pauseBtn").disabled=false;$("pauseBtn").textContent="▶ 続きから再開";status("一時停止中");}else if(paused>0)play(paused);}
function stop(){clear();paused=0;$("pauseBtn").disabled=true;$("pauseBtn").textContent="Ⅱ 一時停止";status("停止中");setKando("");}
function load(raw){stop();state=safe(raw);render();hideError();setKando("");}
$("builtinBtn").onclick=()=>load(window.KUNKUNSHI_SAMPLE);$("importFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{load(JSON.parse(await f.text()));}catch(x){error(x);}finally{e.target.value="";}};$("tempo").oninput=()=>{state.tempo=Number($("tempo").value);$("tempoOut").textContent=`${state.tempo} BPM`;};$("volume").oninput=()=>{const v=Number($("volume").value);$("volumeOut").textContent=`${v}%`;if(gain)gain.gain.value=v/100;};$("playBtn").onclick=()=>{paused=0;play(0);};$("pauseBtn").onclick=pause;$("stopBtn").onclick=stop;document.addEventListener("visibilitychange",()=>{if(document.hidden&&playing)pause();});window.addEventListener("beforeunload",stop);try{load(window.KUNKUNSHI_SAMPLE);}catch(e){error(e);}
